ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  secret: "123456"
  issuer: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  accessTokenExpiration: 900000
  refreshTokenExpiration: 604800000
