apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-town-api
  labels:
    app: blog-town-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-town-api
  template:
    metadata:
      labels:
        app: blog-town-api
        version: v1
    spec:
      containers:
        - name: blog-town-api
          image: blog-town:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: blog-town-config
                  key: jwt.secret
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: blog-town-config
                  key: jwt.issuer
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: blog-town-config
                  key: jwt.audience
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: blog-town-secrets
                  key: google.client.id
                  optional: true
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: blog-town-secrets
                  key: google.client.secret
                  optional: true
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: blog-town-secrets
                  key: github.client.id
                  optional: true
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: blog-town-secrets
                  key: github.client.secret
                  optional: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
      restartPolicy: Always